version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Checks for actions in .github/workflows
    schedule:
      interval: "daily"
    target-branch: "main"
