repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Or the latest stable version
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-merge-conflict
    -   id: detect-private-key
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5 # Or the latest stable ruff version
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
    -   id: ruff-format
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0 # Or the latest stable mypy version
    hooks:
    -   id: mypy
        args:
            - --config-file=mypy.ini
            # Files to check are passed by pre-commit; no explicit path needed here
            # Consider removing --ignore-missing-imports if mypy.ini handles it sufficiently
            - --python-version=3.12
            - --ignore-missing-imports # Keeping for now, but mypy.ini is preferred source of truth
            - --follow-imports=silent
            - --show-column-numbers
            - --namespace-packages
            - --explicit-package-bases
            - --install-types
            - --non-interactive
        additional_dependencies:
          - aiobookoov2==0.3.3 # Match your manifest
          # - homeassistant-stubs # Example if you use HA stubs
          - types-PyYAML
          - types-atomicwrites
