name: CI Checks for Bookoo Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

env:
  DEFAULT_PYTHON: "3.12"

jobs:
  lint-type-test:
    name: Lint, Type Check, and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.5.5 mypy pytest pytest-asyncio pytest-mock freezegun pytest-homeassistant-custom-component
          # Install component dependencies from manifest.json (aiobookoov2)
          # This requires parsing manifest.json or hardcoding, let's assume aiobookoov2 for now
          # A more robust way would be to parse manifest.json for requirements
          pip install aiobookoov2==0.3.4 # Match your current manifest

      - name: Run Ruff Linter
        run: ruff check .

      - name: Run Ruff Formatter Check
        run: ruff format --check .

      - name: Run MyPy Type Checker
        run: mypy --config-file=mypy.ini custom_components/bookoo/

      - name: Run Pytest
        # Set PYTHONPATH so imports from custom_components work correctly
        run: PYTHONPATH=$(pwd) pytest tests/
        # If tests are in tests/components/bookoo, use:
        # run: PYTHONPATH=$(pwd) pytest tests/components/bookoo/
